Experiment No.8

Tools for EDA - Numpy

Name : Akshat Deshmukh

PRN :    25070123008

In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3], [4,5,6]])

print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(4,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a*2

array([20, 40, 60, 80])

In [ ]:
a+5

array([15, 25, 35, 45])

In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.max(a)

np.int64(40)

In [ ]:
np.min(a)

np.int64(10)

In [ ]:
np.sum(a)

np.int64(100)